axon:
  axonserver:
    enabled: false
  kafka:
    bootstrap-servers: localhost:29092,localhost:29094,localhost:29096
    default-topic: Axon.AccountCQRS.Events
    client-id: kafka-axon-account

    message-converter-mode: default # alternative is cloud_event <https://cloudevents.io/>
    properties:
      security.protocol: PLAINTEXT # PLAINTEXT for no security purpose
    consumer:
      event-processor-mode: pooled_streaming
  serializer:
    general: jackson
    events: jackson
    messages: jackson
server:
  port: 20262

spring:
  application:
    name: ACCOUNT-QUERY

# Liquibase configuration  ----------
  liquibase:
    enabled: true
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:16851/db_account_query
    user: itpusr
    password: itp@168
# Jpa configuration ------------------
  datasource:
    url: jdbc:postgresql://localhost:16851/db_account_query
    driver-class-name: org.postgresql.Driver
    username: itpusr
    password: itp@168
  jpa:
    hibernate:
      ddl-auto: none

  # R2DBC configuration
  r2dbc:
    url: r2dbc:postgresql://localhost:16851/db_account_query
    username: itpusr
    password: itp@168
# -----------------------------------
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888
#  security:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:9090
